### ISSUE TITLE
Data simulation and DMR code

### ISSUE THREAD

**Issue by fojackson8** [jasminezhoulab/cfSort#1]
Hi, thanks for the great paper! Are you planning on making your data simulation code available? It would be a valuable resource for benchmarking and training similar deconvolution models (with different references). 

I'd also be interested in the DMR code, as I'm struggling to fully understand how you called DMRs, and how you divided up the genome. Many thanks

**Comment by DashuoLI** [comment]
Hi, thanks for your interest. We didn't perform data simulation directly on the extracted features from the original tissue samples. Instead, we started from aligned reads. Our data simulation is quite simply done with (step 1) sampling reads from aligned reads of an original tissue sample, and (step 2) merging sampled reads from different tissue types. This process can be done using samtools command lines. 

Our marker selection pipeline was adapted from our recent publication (https://doi.org/10.1038/s41467-022-32995-6). You can find the codes here (https://github.com/jasminezhoulab/cfMethyl-Seq).
