### ISSUE TITLE
Questions about cfsort data input and output

### ISSUE THREAD

**Issue by heweihuang** [jasminezhoulab/cfSort#4]
How to generate an input file for the flow data_prep.for_test_only.py from the bedgrah file containing methylated chromosome locations and methylation levels. Is there any relevant process? Because according to the description in supplementary material S5.1, the intermediate conversion process is very complicated.
The prediction result generated from the process model_pred.py is the value of 29 columns in a row. May I ask whether the order of column names is based on 29 names of tissue words, as shown in Table S1 of supplementary data.
Thank you.

**Comment by DashuoLI** [comment]
Thanks for your interest!

The input file cannot be generated from the bedgraph files. The bedgraph files summarize sequencing data as the methylation levels at every CpG site, but generating the input file needs the CpG methylation status on sequencing reads. We are preparing an update of the repository by adding a preprocessing pipeline to generate input files from the bam files.

The tissue names are in alphabetical order, adipose_tissue, adrenal_gland, bladder, blood_vessel, breast, cervix_uteri, colon, esophagus, fallopian_tube, heart, kidney, liver, lung, muscle, nerve, ovary, pancreas, pituitary, prostate, salivary_gland, skin, small_intestine, spleen, stomach, testis, thyroid, uterus, vagina, and WBC.

**Comment by DaGaMs** [comment]
I just had the same question. From my reading of the methods, the per-feature values are

> the fraction of tissue-specific DNA fragments across all individual markers within this merged marker

Where "tissue-specific DNA fragments" are defined as the number of fragments with $\alpha$ values below the $\alpha_{cut}$ value for that marker.

The thing I don't understand is: **where can I find the $\alpha_{cut}$ values as derived from the training data for the ~50000 marker regions?**

I'd be very grateful for your help - I think I can handle the rest of the processing, but that piece of information seems very difficult to re-generate without rerunning the entire marker-identification pipeline, and without it the `cfSort` tool can't be used, as far as I can tell?

**Comment by DashuoLI** [comment]
The $`\alpha_{cut}`$ can be found in the **alpha_threshold** column in cfSort_markers.txt.gz in the marker folder.
