### ISSUE TITLE
Data matrix generation using the alpha cutoff

### ISSUE THREAD

**Issue by pwwang** [jasminezhoulab/cfSort#6]
Hi,

In the supplement information on page 6:

> The tissue-specific DNA fragments were identified at every individual marker as the DNA fragment with 𝛼-value above the marker-specific threshold.

Is this correct? Or should it be "below" instead of "above"?

In order to calculate the feature in the data matrix, should it be the sum of the tissue-specified DNA fragments (referred above) divided by the total DNA fragments in that marker cluster?

**Comment by DashuoLI** [comment]
Hi,

Thank you for catching this typo. It should be **below**. Based on the definition of $\alpha_{cut}$ in the marker discovery in the method section, the tissue-specific DNA fragments are those whose $\alpha$-value is below $\alpha_{cut}$. And yes, the feature in the data matrix is the sum of tissue-specific DNA fragments divided by the total DNA fragments in that marker cluster.

**Comment by pwwang** [comment]
Thanks for the prompt response. That solves our confusion.
